name: AstronomicalData
channels:
  - default
  - conda-forge
  - astropy
dependencies:
  - python>=3.6
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - pytables
  - h5py
  - scipy
  - astropy
  - astroquery
  - astro-gala
  - python-wget
  - pip
  - pip:
    - pyia
